doskey l=dir $*
doskey art=php artisan $*
doskey art-up=php artisan serve $*
doskey art:seed=php artisan db:seed $*
doskey artm:seed=php artisan make:seeder $*
doskey artm:mt=php artisan make:test $*
doskey artm:mo=php artisan make:model $*
doskey art:mi=php artisan migrate $*
doskey art:fr=php artisan migrate:fresh $*
doskey art:ref=php artisan migrate:refresh $*
doskey art:re=php artisan migrate:reset $*
doskey cm=git commit -m $*
doskey st=git status $*
doskey push=git push origin $*
doskey push=git push origin $*
doskey pull=git pull $*
doskey br=git branch $*
doskey ct=git checkout $*
doskey ctb=git checkout -b $*
doskey aa=git add -A $*
doskey mg=git merge $*
doskey tag=git tag -a $*
doskey tagl=git tag -l $*
doskey art:auth=art:cmd=php artisan make:auth $*
doskey art:cmd=php artisan make:command $*
doskey art:controller=php artisan make:controller $*
doskey art:event=php artisan make:event $*
doskey art:job=php artisan make:job $*
doskey art:listener=php artisan make:listener $*
doskey art:mail=php artisan make:mail $*
doskey art:middleware=php artisan make:middleware $*
doskey art:migration=php artisan make:migration $*
doskey art:notification=php artisan make:notification $*
doskey art:policy=php artisan make:policy $*
doskey art:provider=php artisan make:provider $*
doskey art:request=php artisan make:request $*
doskey art:tinker=php artisan tinker $*
cls
